# Change these first
owner: omerxx
repo: upptime # The name of this repository

sites:
  - name: Zesty.co
    url: https://zesty.co
  - name: Zesty Dashboard
    url: https://app.zesty.co
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://app.zesty.co/assets/logo/zesty-logo.svg
  name: Zesty Monitor
  introTitle: "**Real-Time** Cloud Savings"
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
